#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo
echo '🏗️👷 Checking and fixing your styling...';
pnpm run lint -- --fix --strict --max-warnings=0 || (
  echo
  echo 'Found an non-fixable errors, are you serious?'
  echo
  exit 1;
)

echo
echo 'All is well🔥🔥'
echo 'Commiting your work...'
echo
